export const routes = {
  auth: 'auth',
  app: 'app',
  splash: 'splash',
  signin: 'signin',
  signup: 'Create Account',
  profile: 'Profile',
  terms: 'Terms Of Services',
  home: 'Home',
  settings: 'Account',
  forgotPass: 'forgotPass',
  errorForgotPass: 'errorForgotPass',
  profileInterest: 'profileInterest',
  searchScreen: 'searchScreen',
  eventDetail: 'eventDetail',
  verification: 'verification',
  newPass: 'newPas',
  changePass:'changePass',
  changePassSuccess : 'changePassSuccess',
  contact:'contact us',
  aboutUs : 'aboutUs',
  eventList:'eventList',
  myBooking : 'myBooking',
  myBookmark:'myBookmark',
};
